### PR TITLE
Fix hash function

### PR DESCRIPTION
**Pull request by fanatid**
Please review, merge and release ASAP.

### CODE REVIEW

**Comment by wanderer** [comment]
lgtm, @axic @kumavis can we get one more review?

**Comment by kumavis** [comment]
looks good to me 👍

**Comment by kumavis** [comment]
@wanderer please ver bump and publish

**Comment by fanatid** [comment]
@kumavis you in package owners on npmjs, so you also can do this :)

**Comment by fanatid** [comment]
I also recommend add message about wrong hash function to versions `1.2.0`, `1.2.1`, `1.2.2` with [deprecate](https://docs.npmjs.com/cli/deprecate) command

**Comment by kumavis** [comment]
oh! so i am! published as `ethereumjs-tx@1.2.4`
will also deprecate the old ones

**Comment by kumavis** [comment]
thanks @fanatid !

**Pull request merged**
