### PR TITLE
Update Travis to run on Node v8 and v10; Add tests for inherited FakeTransaction functions

### LINKED ISSUE #114: Add tests for inherited FakeTransaction functions
Test coverage for ``FakeTransaction`` is showing [100%](https://coveralls.io/github/ethereumjs/ethereumjs-tx). This is very misleading since all the inherited functionality stays untested from a ``FakeTransaction`` context.

There where different bugs introduced with recent updates https://github.com/ethereumjs/ethereumjs-tx/issues/108 or https://github.com/ethereumjs/ethereumjs-tx/issues/113 which could have been easily caught by expanding the test coverage.

Given the importance and wide usage of the ``FakeTransaction`` version these tests should be added on a high-priority.

### PR DESCRIPTION
**Pull request by chikeichan**
Fixes #114 

Opening this one on top of #131 - I will change merge target to master when #131 is merged.

### CODE REVIEW

**Comment by holgerd77** [comment]
This has a linting error, also ``Node 6`` is not supporting the spread operator. That said we have just decided to [drop Node 6 support](https://github.com/ethereumjs/organization/pull/50) and you can use this PR to update CI to run towards Node 8, 10 and 11 (if you do can you then add a note to your initial PR description so that this won't get forgotten on release notes).

**Comment by holgerd77** [comment]
One procedural note: can you use the PR-marked labels for your pull requests - primarily the WIP and Ready-for-review (only once tests passes) labels? Then it get's easier to judge if a PR is ready. You can also request specific reviewers if you like (not necessarily me).

**Comment by holgerd77** [comment]
That said: thanks for the various PRs! 👍 😄

**Comment by chikeichan** [comment]
> One procedural note: can you use the PR-marked labels for your pull requests - primarily the WIP and Ready-for-review (only once tests passes) labels? Then it get's easier to judge if a PR is ready. You can also request specific reviewers if you like (not necessarily me).

Thanks for the housekeeping notes @holgerd77 ! I will address the comments on various PRs over the next 3-5 days

**Comment by holgerd77** [comment]
👍

**Comment by holgerd77** [comment]
Hi @chikeichan can you bring this up-to-date?

**Comment by alcuadrado** [comment]
This looks good to me. The only method not directly tested is `getSenderPublicKey`, but it gets tested though `getSenderAddress`.

About the travis part. Should it include v11? It is the [Current version](https://github.com/nodejs/Release#release-schedule) now, but that'll change in a few weeks, and its EOL is in two months.

**Pull request merged**
