### PR TITLE
Fix signing eip155 transactions

### PR DESCRIPTION
**Pull request by holgerd77**
I will open this new PR from the ``fix-signing-eip155-transactions`` branch which was displayed to me by GitHub. Can someone have a look and approve if considered to be side-effect-free to merge this again?

### CODE REVIEW

**Comment by danjm** [comment]
@holgerd77 This looks correct to me.

One tangible piece of verification: if we check the stats on the diff of this branch to master and https://github.com/alcuadrado/ethereumjs-tx/tree/typescript-migration to, we get an identical result. I did this locally.

Screenshot from 2019-04-29 08-20-16

**Comment by holgerd77** [comment]
@danjm Cool 👍, thanks for checking! 😄

Will then merge here finally.

**Comment by holgerd77** [comment]
@danjm @alcuadrado @s1na Respectively, can one of you guys explicitly approve here?

**Comment by danjm** [comment]
@holgerd77 Approved!

**Pull request merged**
