### PR TITLE
add babelify transform

### PR DESCRIPTION
**Pull request by yann300**

### CODE REVIEW

**Comment by kumavis** [comment]
this was removed since we publish the compiled version
https://github.com/ethereumjs/ethereumjs-tx/blob/master/package.json#L5

**Comment by yann300** [comment]
and is this possible to readd it ? :)  as it will not add other dependency ....
We could find a solution to this but that would be great if we can have it when building remix.
If not nop.
thanks

**Comment by kumavis** [comment]
can you explain why this is an issue for remix - are you not using the main export?

**Comment by yann300** [comment]
yes but the build process uses browserify/babelify to es5 transform the code. 
That was as far as i remember a better practice to include the process in the dependency rather than in the root module. Anyway, that's up to you,  we can also do without nop

**Comment by kumavis** [comment]
@yann300 so did removing this break something for you? - im surprised you noticed the change

**Comment by yann300** [comment]
That does not break anything but then the remix build contains es6 class (`class Transaction`) .

**Comment by kumavis** [comment]
@yann300 so thats surprising to me because the module main should already be es5 transpiled and not contain the `class` syntax

https://github.com/ethereumjs/ethereumjs-tx/blob/master/package.json#L5

can you confirm that you are 
1) using the module's default entrypoint
2) it contains the `class` syntax

**Comment by yann300** [comment]
yeah I can't confirm `using the module's default entrypoint` will check that asap

**Comment by yann300** [comment]
referencing the npm module instead of git url and using the published es5 build, everything ok

**Pull request closed without merging**
