### PR TITLE
EIP155 - allow v value to be greater than one byte

### LINKED ISSUE #56: EIP155 - fails on chainId's greater than one byte
infuranet testnet uses chainId `0x16b2`, which fails to sign bc when it sets itself to `v` for hashing, it fails bc `v.length` > 1 byte.

Not sure how well this works with other clients.
This was totally brought up in the [EIP155](https://github.com/ethereum/EIPs/issues/155) thread, with little attention.

### PR DESCRIPTION
**Pull request by kumavis**
Fixes #56
also see
https://github.com/ethereum/EIPs/issues/155#issuecomment-276075645
https://github.com/ethereum/tests/issues/142

### CODE REVIEW

**Comment by kumavis** [comment]
@wanderer @axic

**Comment by kumavis** [comment]
Thank you @fanatid

**Comment by fanatid** [comment]
@kumavis still not clear for me from EIP thread, is standard allows chainId be multi-byte?

**Comment by kumavis** [comment]
de-facto standard -- its handled correctly by geth and parity

**Comment by fanatid** [comment]
Thank you.
LGTM

**Comment by kumavis** [comment]
@wander plz bump and publish

**Pull request merged**
