### PR TITLE
Add TS types to repo

### PR DESCRIPTION
**Pull request by HenryNguyen5**
Related to https://github.com/ethereumjs/ethereumjs-wallet/pull/30

### CODE REVIEW

**Comment by LogvinovLeon** [comment]
Hi. I've just submitted ethereumjs-tx types to DefinitelyTyped
https://www.npmjs.com/package/@types/ethereumjs-tx
Those seem to be more complete though. Feel free to submit a PR to DT to fix that.

**Comment by LogvinovLeon** [comment]
Also - seems like this PR will have no effect unless you also have a types field in package.json

**Comment by alcuadrado** [comment]
I'm closing this PR. This project has been migrated to TypeScript 🎉

**Comment by HenryNguyen5** [comment]
Awesome, nice job!

**Pull request closed without merging**
